default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rateathon-dev

test:
  <<: *default
  database: rateathon-test

production:
  <<: *default
  database: rateathon
